### ISSUE TITLE
Should we fork this open source library for travel diary summarization originally built by RSG to this repo?

### ISSUE THREAD

**Issue by Ennazus** [ZephyrTransport/travel-diary-survey-tools#1]
https://github.com/RSGInc/travelSurveyTools

PSRC was thinking we'd fork to our own account, but Zephyr might be better to be more open.

We could make the library work across industry and be less proprietary.
I'd be okay with being the gatekeeper. Which would we mean bug fixes and feature improvements would be slow moving.
PSRC does not want to pay for long term maintenance of the package to one specific consultant.

**Comment by lmz** [comment]
Good idea!  Done: https://github.com/ZephyrTransport/travelSurveyTools

I gave the https://github.com/orgs/ZephyrTransport/teams/travel-diary-survey-tools admin access.
